build:
   artifacts:
        expire_in: 1 week
        paths:
        - ./*.zip
   image: ubuntu:20.04
   script:
       - apt-get update && apt-get -y install git zip
       - git submodule update --init --recursive
       - zip -r crackle.zip .
