build:
   artifacts:
        expire_in: 1 week
        paths:
        - ./*.zip
   image: ubuntu:20.04
   script:
       - apt-get update && apt-get -y install git zip python
       - git submodule update --init --recursive
       - mkdir crackle.d
       - mv * crackle.d || mv crackle.d crackle
       - mv .git* crackle && zip -r crackle.zip crackle
